添加启动尺寸适应
lzd-1230/Debugging-assistant pull request #1
Opened 2023-11-04 16:24 UTC by Thoelc

您好我发现这个项目在我的电脑运行启动时初始窗口非常小，应该是电脑屏幕不同影响，所以我修改成初始化根据电脑屏幕大小自适应为0.5尺寸
![image](https://github.com/lzd-1230/Debugging-assistant/assets/61264320/3dcbc6b4-5295-41c0-b9bb-c02c5cdfa6c2)
修改后
![image](https://github.com/lzd-1230/Debugging-assistant/assets/61264320/913df764-3202-45d5-ad2e-d176cef96133)

2023-11-05 13:35 UTC, lzd-1230 commented
您好, 感谢指出, 您可以看看如何在ui文件中改善这个窗口大小，你目前修改的这个`ui_Widget.py`会在每次修改ui文件(build.bat)之后被覆盖掉，因此你可以再看下如何在ui文件中进行修改

2023-11-06 18:27 UTC, Thoelc commented
> 您好, 感谢指出, 您可以看看如何在ui文件中改善这个窗口大小，你目前修改的这个`ui_Widget.py`会在每次修改ui文件(build.bat)之后被覆盖掉，因此你可以再看下如何在ui文件中进行修改

QApplication是Qt后台管理方法，Qtdesiner中无法设定,ui文件只能是固定大小，但是可以加在您的myWidget里面来修改，顺便家里适应高分辨率缩放适应功能

2023-11-08 01:25 UTC, lzd-1230 commented
好的，我稍后测试一下就给你merge

2023-11-08 02:45 UTC, lzd-1230 requested changes
功能上没问题，第七行可以删掉, QApplication重复import了

2023-11-08 02:46 UTC, lzd-1230 commented on myWidget.py
> +from PyQt5.QtWidgets import QApplication
删除这一行再提交一次就ok了

2023-11-08 03:36 UTC, merged